---
version: "3.7"

services:
  app:
    command: ["bundle", "exec", "ruby", "app.rb", "-o", "0.0.0.0"]
    image: sunakan/erapp:latest
    build: .
    ports:
      - 4567:4567
    volumes:
      - ./:/app
